version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  groups:
    aws-gems:
      patterns:
        - "aws-*"
  open-pull-requests-limit: 10
  reviewers:
    - "ministryofjustice/crm7team"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  groups:
    npm-babel:
      patterns:
        - "*babel*"
    npm-jest:
      patterns:
        - "jest*"
  open-pull-requests-limit: 10
  reviewers:
    - "ministryofjustice/crm7team"

