# List of providers (office codes and/or emails)
# who can use the service (phased private MVP access).
#
# If a provider has more than one office code, then
# access is granted if any code is allowed.
#
# If ALL is specified then any authenticated user
# can access that service
#
localhost:
  office_codes:
    # dummy/testing office codes
    - 1A123B
    - 2A555X
    - 1K022G
    - 0A719G
    - 0Z981E
    - AAAAAA
    - XXXXXX

development:
  office_codes:
    # dummy/testing office codes
    - 1A123B
    - 2A555X
    - 1K022G
    - 0A719G
    - 0Z981E
    - AAAAAA
    - XXXXXX

    # Test user office from portal A.CLARK - with eForms role - (see 1Password for login details)
    # - 0X416R

    # Test user office from portal 07RJONES - without eForms role - (see 1Password for login details)
    # - 0Q316L

uat:
  office_codes:
    # dummy/testing office codes
    - 1A123B
    - 2A555X
    - 1K022G
    - 0A719G
    - 0Z981E
    - AAAAAA
    - XXXXXX

    # Test user office from portal A.CLARK - with eForms role - (see 1Password for login details)
    # - 0X416R

    # Test user office from portal 07RJONES - without eForms role - (see 1Password for login details)
    # - 0Q316L

production:
  office_codes:
    # dummy user/office
    # - 2N232W
